version: '3'

services:
  backend:
    restart: always
    build: ./backend
    expose:
      - "8000"
    links:
      - postgres:postgres
    env_file: 
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 run:app

  frontend:
    restart: always
    build: ./frontend

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "8000:8000"
    links:
      - backend:backend

  data:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    command: "true"

  postgres:
    restart: always
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  db-data:
